name: CI with MinGW (Windows)

on:  # Trigger workflow on pushes to the master branch
  push:
    branches:
      - master
      - feature/*
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest  # Or any other compatible Linux runner

    env:
      RAYLIB_VERSION: '5.0.0'  # Replace with desired Raylib version

    steps:
    - uses: actions/checkout@v2

    - name: Download Raylib
      run: |
        curl -L -k -o raylib.tar.gz https://github.com/raysan5/raylib/releases/download/5.0/raylib-5.0_linux_amd64.tar.gz
        tar -xzvf raylib.tar.gz
        mv raylib-5.0_linux_amd64 raylib

    - name: Compile
      run: |
        ls
        mkdir build
        gcc src/*.c -o build/ngn \
        -I./raylib/include -L./raylib/lib \
        -lraylib -lm -lpthread
        cp -r resources build/resources

    - name: Create archive
      run: |
        cp -r resources build/resources

    - name: Upload artifacts  # Upload compiled program for future reference
      uses: actions/upload-artifact@v3
      with:
        name: build-linux
        path: build

  build-windows:
    runs-on: ubuntu-latest  # Or any other compatible Linux runner

    steps:
    - uses: actions/checkout@v2

    - name: Run script
      run: ./build-windows.sh

    - name: Create archive
      run: |
        mkdir build
        cp -r resources build/resources
        mv ngn.exe build/ngn.exe

    - name: Upload artifacts  # Upload compiled program for future reference
      uses: actions/upload-artifact@v3
      with:
        name: build-windows
        path: build
