name: CI with MinGW (Windows)

on:  # Trigger workflow on pushes to the master branch
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest  # Specify Windows runner

    env:
      RAYLIB_VERSION: '5.0.0'  # Replace with desired Raylib version

    steps:
      - uses: actions/checkout@v3  # Checkout code from repository

      - name: Install MinGW
        uses: msysbuild/actions/vcpkg@v1  # Example action to install dependencies
        with:
          packages: mingw-w64-x86-gcc  # Adjust package names as needed

      - name: Download Raylib
        uses: actions/download@v2
        with:
          url: https://github.com/raysan5/raylib/releases/download/v${{ env.RAYLIB_VERSION }}/raylib-v${{ env.RAYLIB_VERSION }}-mingw32-x86.zip
          dest: raylib

      - name: Set up Raylib environment variables
        run: |
          echo "RAYLIB_DIR=$(pwd)/raylib" >> $GITHUB_ENV
          echo "PATH=$RAYLIB_DIR/bin:$PATH" >> $GITHUB_ENV

      - name: Compile
        run: gcc src/*.c -o ngn -I${RAYLIB_DIR}/include -L${RAYLIB_DIR}/lib -lraylib -lm -lgdi32 -lwinmm -lpthread -lws2_32 -static

      - name: Upload artifacts  # Upload compiled program for future reference
        uses: actions/upload-artifact@v3
        with:
          name: ngn
          path: ngn